"""Model-collapse pipeline (Options A + C).

Each generation g >= 1 trains a FRESH model on a pool mixing:
    real_fraction        freshly-sampled REAL sequences
    (1 - real_fraction)  SYNTHETIC sequences generated by generation g-1
Sweeping real_fraction traces a dose-response curve for collapse (Option C).
Every generation logs the robust induction-circuit probe (Option A) and, in
extended mode, the per-context diversity of the free next-symbol choice.

Synthetic generation keeps a real study/query CONTEXT and lets the model fill the
answer slots autoregressively (each sample conditions the next):
    gen_queries="first"  only the first query label is model-generated (the
                         original design: the other K-1 query labels keep their
                         ground-truth targets, so induction is re-taught from real
                         labels every generation even at real_fraction=0)
    gen_queries="all"    all K query labels are model-generated (fully recursive)
    extended mode additionally generates sq2 and lq2 in both settings.

Reliability safeguards (a failed optimisation must not be read as collapse):
  * pool split 90/10 into train / validation; the test set is fresh real data;
  * convergence gate: a generation is 'converged' if its validation accuracy on
    the pool's query labels reaches gate * (fraction of those labels that are
    correct). Otherwise it is retrained from a new init (up to max_retries);
    retries are logged, and if all fail the best attempt is kept, flagged
    converged=False;
  * collision-free seeding: init seed = seed*1000 + 10*g + attempt, so different
    seeds never share an initialisation (previously seed s, gen 1 == seed s+1, gen 0).
"""
import dataclasses
import time

import numpy as np
import torch

from . import data as datamod
from . import metrics, probes
from .config import resolve_device
from .data import TensorDataset
from .train import train_model


def query_positions(cfg):
    K = cfg.n_pairs
    return list(range(2 * K, 4 * K, 2))


@torch.no_grad()
def generate_dataset(model, cfg, n, rng, device, temperature=1.0, gen_queries="first"):
    model.eval()
    batch = datamod.make_batch(cfg, n, rng, device)
    batch["true_targets"] = batch["targets"].clone()
    idx = batch["idx"].clone()
    targets = batch["targets"].clone()
    rows = torch.arange(n, device=device)
    L = cfg.max_len
    K = cfg.n_pairs

    qps = query_positions(cfg) if gen_queries == "all" else [2 * K]
    gen_positions = qps + ([4 * K - 1, 4 * K] if cfg.mode == "extended" else [])
    for pos in gen_positions:
        logits = model(idx)[rows, pos] / temperature
        sample = torch.distributions.Categorical(logits=logits).sample()
        targets[:, pos] = sample
        if pos + 1 < L:
            idx[:, pos + 1] = sample

    batch["idx"] = idx
    batch["targets"] = targets
    batch["query_tgt"] = targets[:, 2 * K].clone()
    return batch


def _real(cfg, n, rng, device):
    b = datamod.make_batch(cfg, n, rng, device)
    b["true_targets"] = b["targets"].clone()
    return b


@torch.no_grad()
def _pool_val_acc(model, batch, cfg):
    qp = query_positions(cfg)
    pred = model(batch["idx"]).argmax(-1)
    return (pred[:, qp] == batch["targets"][:, qp]).float().mean().item()


def _label_correctness(batch, cfg):
    qp = query_positions(cfg)
    return (batch["targets"][:, qp] == batch["true_targets"][:, qp]).float().mean().item()


def _record(g, model, cfg, eval_rng, device, eval_batch, extra):
    test = datamod.make_batch(cfg, eval_batch, eval_rng, device)
    circ = probes.circuit_probe(model, test, cfg)
    rec = {
        "generation": g,
        "query_acc": metrics.query_accuracy(model, test),          # first query (legacy)
        "query_acc_all": circ["query_acc_all"],                    # all K queries
        "query_ppl": metrics.query_perplexity(model, test),
        "induction": circ["induction_legacy"],                     # legacy probe
        "circuit": circ,
    }
    if cfg.mode == "extended":
        rec["cond_diversity"] = metrics.conditional_diversity(model, test, cfg)
        gen = generate_dataset(model, cfg, eval_batch, eval_rng, device)
        gp = 4 * cfg.n_pairs - 1
        sym = gen["targets"][:, gp]
        rec["slot"] = metrics.slot_stats(sym, gen["idx"], cfg.n_pairs)
        rec["diversity"] = metrics.distribution_stats(sym.cpu().numpy(), cfg.n_symbols)
        rec["kl_uniform"] = metrics.kl_to_uniform(sym.cpu().numpy(), cfg.n_symbols)
    rec.update(extra)
    return rec


def _train_gated(cfg, seed, g, train_sampler, val_batch, probe_batch, label_ok,
                 gate, max_retries, real_gate):
    """Train (with retries) until the convergence gate passes."""
    attempts, best = [], None
    for a in range(max_retries + 1):
        c = dataclasses.replace(cfg, seed=seed * 1000 + 10 * g + a)
        t0 = time.time()
        model, hist = train_model(c, train_sampler, val_sampler=None,
                                  probe_batch=probe_batch, log=False)
        val_acc = _pool_val_acc(model, val_batch, cfg)
        target = real_gate if label_ok is None else gate * label_ok
        ok = val_acc >= target
        attempts.append({"init_seed": c.seed, "val_acc": val_acc, "target": target,
                         "passed": ok, "seconds": round(time.time() - t0, 1),
                         "transition_step": next((r["step"] for r in hist
                                                  if r.get("induction", 0) > 0.5), None)})
        if best is None or val_acc > best[1]:
            best = (model, val_acc)
        if ok:
            break
    # A model with NO induction still scores ~0.45 by guessing among the labels
    # present in context. If the pool's labels are mostly wrong the gate target
    # falls near that baseline and can no longer separate 'failed to converge'
    # from 'faithfully fit a corrupted pool' -> flag it; use circuit/causal_drop.
    informative = label_ok is None or label_ok >= 0.6
    return best[0], {"attempts": attempts, "retries": len(attempts) - 1,
                     "converged": attempts[-1]["passed"],
                     "gate_informative": informative}


def run_collapse(cfg, n_generations, real_fraction, seed, pool_size=20000,
                 temperature=1.0, gen_queries="first", gate=0.9, real_gate=0.9,
                 max_retries=3, verbose=False):
    device = resolve_device(cfg.device)
    cfg = dataclasses.replace(cfg, device=device)
    rng = np.random.default_rng(seed)                     # pools + generation
    eval_rng = np.random.default_rng(seed + 424_242)      # test sets (disjoint stream)
    probe_batch = datamod.make_batch(cfg, cfg.eval_batch, eval_rng, device)
    n_val = max(512, pool_size // 10)

    # generation 0: infinite fresh real data; gate on a held-out real batch
    real_sampler = lambda bs, r, dev: datamod.make_batch(cfg, bs, r, dev)
    val0 = _real(cfg, n_val, eval_rng, device)
    model, info = _train_gated(cfg, seed, 0, real_sampler, val0, probe_batch,
                               None, gate, max_retries, real_gate)
    records = [_record(0, model, cfg, eval_rng, device, cfg.eval_batch,
                       {**info, "pool_label_correct": 1.0, "synthetic_fraction": 0.0})]
    if verbose:
        _print(records[-1])

    for g in range(1, n_generations):
        total = pool_size + n_val
        n_real = int(round(total * real_fraction))
        n_syn = total - n_real
        parts = []
        if n_real > 0:
            parts.append(TensorDataset(_real(cfg, n_real, rng, device)))
        if n_syn > 0:
            parts.append(TensorDataset(generate_dataset(
                model, cfg, n_syn, rng, device, temperature, gen_queries)))
        pool = parts[0] if len(parts) == 1 else TensorDataset.concat(*parts)
        # shuffle, then split into train / validation
        perm = torch.from_numpy(rng.permutation(pool.n)).to(pool.data["idx"].device)
        data = {k: v[perm] for k, v in pool.data.items()}
        val = {k: v[:n_val] for k, v in data.items()}
        train = TensorDataset({**{k: v[n_val:] for k, v in data.items()}, **pool.meta})
        label_ok = _label_correctness(val, cfg)
        sampler = lambda bs, r, dev, train=train: train.sample(bs, r)

        model, info = _train_gated(cfg, seed, g, sampler, val, probe_batch,
                                   label_ok, gate, max_retries, real_gate)
        rec = _record(g, model, cfg, eval_rng, device, cfg.eval_batch,
                      {**info, "pool_label_correct": _label_correctness(data, cfg),
                       "synthetic_fraction": n_syn / total})
        records.append(rec)
        if verbose:
            _print(rec)
    return records


def _print(rec):
    c = rec["circuit"]
    s = (f"gen {rec['generation']:2d} | acc_all {rec['query_acc_all']:.3f} | "
         f"ind_best {c['induction_best']:.3f} ({c['circuit_type'][:5]}) | "
         f"causal {c['causal_drop']:.3f} | labels_ok {rec['pool_label_correct']:.3f} | "
         f"retries {rec['retries']}{'' if rec['converged'] else ' NOT-CONVERGED'}")
    if "cond_diversity" in rec:
        s += (f" | condH {rec['cond_diversity']['cond_entropy']:.3f} | "
              f"slotH {rec['slot']['slot_entropy']:.3f} | "
              f"off {rec['cond_diversity']['off_context']:.3f}")
    print(s, flush=True)
