"""Model-collapse pipeline (Options A + C).

Each generation g >= 1 trains on a pool mixing:
    real_fraction        freshly-sampled REAL sequences
    (1 - real_fraction)  SYNTHETIC sequences generated by generation g-1
Sweeping real_fraction traces a dose-response curve for collapse (Option C).
Every generation logs induction-head strength (Option A) and, in extended mode,
the diversity of the model's generated next-symbol distribution.

Synthetic generation keeps a real induction context and lets the model fill the
query/generative slots autoregressively (each sample conditions the next), so the
model's own biases enter the next generation's targets.
"""
import numpy as np
import torch

from . import data as datamod
from . import metrics, probes
from .config import resolve_device
from .data import TensorDataset
from .train import train_model


@torch.no_grad()
def generate_dataset(model, cfg, n, rng, device, temperature=1.0):
    model.eval()
    batch = datamod.make_batch(cfg, n, rng, device)
    idx = batch["idx"].clone()
    targets = batch["targets"].clone()
    query_tgt = batch["query_tgt"].clone()
    rows = torch.arange(n, device=device)
    L = cfg.max_len

    K = cfg.n_pairs
    query_pos = 2 * K
    gen_positions = [query_pos] + ([4 * K - 1, 4 * K] if cfg.mode == "extended" else [])
    for pos in gen_positions:
        logits = model(idx)[rows, pos] / temperature
        sample = torch.distributions.Categorical(logits=logits).sample()
        targets[:, pos] = sample
        if pos + 1 < L:
            idx[:, pos + 1] = sample
        if pos == query_pos:
            query_tgt = sample

    batch["idx"] = idx
    batch["targets"] = targets
    batch["query_tgt"] = query_tgt
    return batch


def _record(g, model, cfg, rng, device, eval_batch):
    real = datamod.make_batch(cfg, eval_batch, rng, device)
    rec = {
        "generation": g,
        "query_acc": metrics.query_accuracy(model, real),
        "query_ppl": metrics.query_perplexity(model, real),
        "induction": probes.induction_strength(model, real, cfg),
    }
    if cfg.mode == "extended":
        gen = generate_dataset(model, cfg, eval_batch, rng, device)
        gp = gen["gen_symbol_pos"]
        sym = gen["targets"][:, gp].cpu().numpy()
        rec["diversity"] = metrics.distribution_stats(sym, cfg.n_symbols)
        rec["kl_uniform"] = metrics.kl_to_uniform(sym, cfg.n_symbols)
    return rec


def run_collapse(cfg, n_generations, real_fraction, seed,
                 pool_size=20000, temperature=1.0, verbose=False):
    device = resolve_device(cfg.device)
    rng = np.random.default_rng(seed)

    real_sampler = lambda bs, r, dev: datamod.make_batch(cfg, bs, r, dev)
    probe_batch = datamod.make_batch(cfg, cfg.eval_batch, rng, device)

    cfg.seed = seed
    model, _ = train_model(cfg, real_sampler, val_sampler=real_sampler,
                           probe_batch=probe_batch, log=verbose)
    records = [_record(0, model, cfg, rng, device, cfg.eval_batch)]

    for g in range(1, n_generations):
        n_real = int(round(pool_size * real_fraction))
        n_syn = pool_size - n_real
        parts = []
        if n_real > 0:
            parts.append(TensorDataset(datamod.make_batch(cfg, n_real, rng, device)))
        if n_syn > 0:
            parts.append(TensorDataset(
                generate_dataset(model, cfg, n_syn, rng, device, temperature)))
        pool = parts[0] if len(parts) == 1 else TensorDataset.concat(*parts)
        sampler = lambda bs, r, dev: pool.sample(bs, r)

        cfg.seed = seed + g
        model, _ = train_model(cfg, sampler, val_sampler=real_sampler,
                               probe_batch=probe_batch, log=False)
        rec = _record(g, model, cfg, rng, device, cfg.eval_batch)
        records.append(rec)
        if verbose:
            extra = (f" | norm_entropy={rec['diversity']['normalised_entropy']:.3f}"
                     if "diversity" in rec else "")
            print(f"gen {g:2d} | query_acc {rec['query_acc']:.3f} | "
                  f"induction={rec['induction']:.3f}{extra}")
    return records
